// src/config/spoke-registry.ts — single source of truth for all mini-apps and service spokes.

export type PaymentProvider = 'honor' | 'stripe' | 'square'
export type SpokeStatus = 'live' | 'gated' | 'hidden'
export type SpokeIndustry = 'general' | 'cannabis' | 'healthcare' | 'restaurant'

export interface SpokeConfig {
  slug: string
  route: string
  title: string
  shortTitle: string
  description: string          // Used in <head> meta AND GatedSpokePlaceholder body
  targetKeyword: string        // Primary SEO keyword
  lawRef: string               // Legal citation shown on page
  badge: string                // e.g. 'SB 553 Compliant'
  suggestedPrice: number       // USD, shown in ContributionBanner
  monetized: boolean           // Show ContributionBanner?
  paymentProvider: PaymentProvider
  status: SpokeStatus
  liveDate?: string            // ISO date — for 'coming soon' copy
  industry?: SpokeIndustry[]   // Industries with special variants
  accentColor: 'indigo' | 'cyan' | 'violet' | 'rose' | 'amber'
}

export const spokeRegistry: Record<string, SpokeConfig> = {
  // ── TOOLS (live) ──────────────────────────────────────────────────────────
  hpp: {
    slug: 'hpp',
    route: '/tools/hpp',
    title: 'Harassment Prevention Program (HPP) Toolkit',
    shortTitle: 'HPP Toolkit',
    description: 'Complete California HPP toolkit — SB 1343 compliant policy template, 4 DFEH-defensible forms, 1-hour employee training agenda, 2-hour supervisor training agenda, and sign-in templates. $149 one-time.',
    targetKeyword: 'California harassment prevention program toolkit SB 1343',
    lawRef: 'Gov. Code § 12950.1 (SB 1343 / AB 1825)',
    badge: 'SB 1343 Compliant',
    suggestedPrice: 149,
    monetized: true,
    paymentProvider: 'honor',
    status: 'live',
    industry: ['general', 'cannabis', 'restaurant'],
    accentColor: 'indigo',
  },
  wvpp: {
    slug: 'wvpp',
    route: '/tools/wvpp',
    title: 'Workplace Violence Prevention Plan (WVPP) Toolkit',
    shortTitle: 'WVPP Toolkit',
    description: 'SB 553 compliant WVPP for California employers — written plan, hazard assessment, 5 Cal/OSHA forms, and 60-minute training facilitator guide. Required since July 1, 2024. $199 one-time.',
    targetKeyword: 'California WVPP template SB 553 workplace violence prevention plan',
    lawRef: 'Labor Code § 6401.9 (SB 553)',
    badge: 'SB 553 / Cal/OSHA Required',
    suggestedPrice: 199,
    monetized: true,
    paymentProvider: 'honor',
    status: 'live',
    industry: ['general', 'cannabis', 'restaurant'],
    accentColor: 'cyan',
  },
  iipp: {
    slug: 'iipp',
    route: '/tools/iipp',
    title: 'Injury & Illness Prevention Program (IIPP) Toolkit',
    shortTitle: 'IIPP Toolkit',
    description: 'California IIPP toolkit — 9-section written program, 6 Cal/OSHA forms, 30-minute training guide, and Cal/OSHA 300 log template. Required for ALL California employers. $199 one-time.',
    targetKeyword: 'California IIPP template 8 CCR 3203 injury illness prevention program',
    lawRef: 'Labor Code § 6401.7 / 8 CCR § 3203',
    badge: '8 CCR § 3203 Required',
    suggestedPrice: 199,
    monetized: true,
    paymentProvider: 'honor',
    status: 'live',
    industry: ['general', 'cannabis', 'restaurant'],
    accentColor: 'violet',
  },
  kyr: {
    slug: 'kyr',
    route: '/tools/kyr',
    title: 'Know Your Rights Notice Package (SB 294)',
    shortTitle: 'KYR Toolkit',
    description: 'SB 294 compliant Know Your Rights notice package — all 13 required rights, employee acknowledgment form, emergency contact form, distribution log, annual checklist, and Spanish-language bonus. $49 one-time.',
    targetKeyword: 'California SB 294 know your rights notice template employer',
    lawRef: 'Labor Code § 2810.5 (SB 294 / SB 616)',
    badge: 'SB 294 Required — Annual',
    suggestedPrice: 49,
    monetized: true,
    paymentProvider: 'honor',
    status: 'live',
    industry: ['general', 'cannabis', 'restaurant'],
    accentColor: 'rose',
  },

  // ── SPOKES (services, live) ────────────────────────────────────────────────
  'compliance-audit': {
    slug: 'compliance-audit',
    route: '/spokes/compliance-audit',
    title: 'HR Compliance Audit',
    shortTitle: 'HR Audit',
    description: 'Comprehensive California HR compliance audit — I-9 review, employee file structure, wage-and-hour classification, and local municipality ordinance checks for small businesses.',
    targetKeyword: 'California HR compliance audit small business',
    lawRef: 'Labor Code §§ 226, 1174 / 8 CCR § 11000+',
    badge: 'California HR',
    suggestedPrice: 0,
    monetized: false,
    paymentProvider: 'honor',
    status: 'live',
    accentColor: 'indigo',
  },
  'labor-law': {
    slug: 'labor-law',
    route: '/spokes/labor-law',
    title: 'Wage-and-Hour Cleanup',
    shortTitle: 'Wage & Hour',
    description: 'California wage-and-hour compliance review — meal/rest breaks, overtime, paystub compliance, mandatory postings, leaves of absence, and contractor vs. employee classification.',
    targetKeyword: 'California wage and hour compliance small business',
    lawRef: 'Labor Code §§ 510, 512, 226 / IWC Wage Orders',
    badge: 'CA Labor Code',
    suggestedPrice: 0,
    monetized: false,
    paymentProvider: 'honor',
    status: 'live',
    accentColor: 'amber',
  },
  handbook: {
    slug: 'handbook',
    route: '/spokes/handbook',
    title: 'Employee Handbook Development',
    shortTitle: 'Handbook',
    description: 'Custom California employee handbook — at-will clauses, state-mandated anti-harassment and leave policies, company standards, and annual regulatory updates for small businesses.',
    targetKeyword: 'California employee handbook small business custom',
    lawRef: 'Gov. Code § 12950 / Labor Code § 2810.5',
    badge: 'California Compliant',
    suggestedPrice: 0,
    monetized: false,
    paymentProvider: 'honor',
    status: 'live',
    accentColor: 'cyan',
  },
  'manager-support': {
    slug: 'manager-support',
    route: '/spokes/manager-support',
    title: 'Manager Support & Coaching',
    shortTitle: 'Manager Support',
    description: 'Hands-on HR support for California managers — corrective action documentation, internal investigations, termination checklists, and day-to-day people problem escalation.',
    targetKeyword: 'California HR manager support corrective action termination',
    lawRef: 'FEHA / Labor Code §§ 98.6, 1102.5',
    badge: 'Operational HR',
    suggestedPrice: 0,
    monetized: false,
    paymentProvider: 'honor',
    status: 'live',
    accentColor: 'violet',
  },
  'harassment-prevention': {
    slug: 'harassment-prevention',
    route: '/spokes/harassment-prevention',
    title: 'Harassment Prevention',
    shortTitle: 'Harassment Prevention',
    description: 'California harassment prevention training and policy implementation — SB 1343 compliant for employers with 5+ employees. Live training delivery, policy drafting, and complaint procedure setup.',
    targetKeyword: 'California harassment prevention training SB 1343 small business',
    lawRef: 'Gov. Code § 12950.1 (SB 1343)',
    badge: 'SB 1343 Compliant',
    suggestedPrice: 0,
    monetized: false,
    paymentProvider: 'honor',
    status: 'live',
    accentColor: 'indigo',
  },
  'workplace-violence': {
    slug: 'workplace-violence',
    route: '/spokes/workplace-violence',
    title: 'Workplace Violence Prevention',
    shortTitle: 'WVPP Services',
    description: 'SB 553 workplace violence prevention plan development, hazard assessment, Cal/OSHA form setup, and annual training delivery for California employers.',
    targetKeyword: 'SB 553 workplace violence prevention plan California employer',
    lawRef: 'Labor Code § 6401.9 (SB 553)',
    badge: 'SB 553 Required',
    suggestedPrice: 0,
    monetized: false,
    paymentProvider: 'honor',
    status: 'live',
    accentColor: 'cyan',
  },
  onboarding: {
    slug: 'onboarding',
    route: '/spokes/onboarding',
    title: 'Onboarding Systems',
    shortTitle: 'Onboarding',
    description: 'California-compliant onboarding systems — offer letters, new-hire packets, I-9 process, orientation flow, and background check procedures for small businesses.',
    targetKeyword: 'California onboarding system small business compliant',
    lawRef: 'Labor Code §§ 2810.5, 98 / 8 CCR § 11090',
    badge: 'California Compliant',
    suggestedPrice: 0,
    monetized: false,
    paymentProvider: 'honor',
    status: 'live',
    accentColor: 'rose',
  },
  'hr-support': {
    slug: 'hr-support',
    route: '/spokes/hr-support',
    title: 'Ongoing HR Support',
    shortTitle: 'Fractional HR',
    description: 'Fractional, project-based, or on-call HR support for California small businesses — compliance check-ins, regulatory alerts, and priority escalation without a full-time HR hire.',
    targetKeyword: 'fractional HR support California small business',
    lawRef: 'All CA Labor Codes',
    badge: 'On-Call HR',
    suggestedPrice: 0,
    monetized: false,
    paymentProvider: 'honor',
    status: 'live',
    accentColor: 'amber',
  },

  // ── GATED SPOKES (SEO placeholder, not yet built) ──────────────────────────
  'paga-defense': {
    slug: 'paga-defense',
    route: '/tools/paga-defense',
    title: 'PAGA Defense Readiness Assessment',
    shortTitle: 'PAGA Defense',
    description: 'California PAGA defense readiness assessment — evaluate your exposure under AB 2288 reformed penalty structure, cure provision eligibility, and documentation quality before a claim is filed.',
    targetKeyword: 'California PAGA defense AB 2288 employer assessment',
    lawRef: 'Labor Code §§ 2698–2699.6 (AB 2288)',
    badge: 'AB 2288 Updated',
    suggestedPrice: 99,
    monetized: true,
    paymentProvider: 'honor',
    status: 'gated',
    liveDate: '2026-07-01',
    accentColor: 'amber',
  },
  'separation-checklist': {
    slug: 'separation-checklist',
    route: '/tools/separation-checklist',
    title: 'California Termination & Separation Checklist',
    shortTitle: 'Separation Checklist',
    description: 'California-compliant termination checklist — final pay timing (Labor Code § 201-203), COBRA notice, WARN Act threshold calculator, reference policy, and separation agreement guidance.',
    targetKeyword: 'California termination checklist final pay WARN Act employer',
    lawRef: 'Labor Code §§ 201-203 / WARN Act / COBRA',
    badge: 'CA Labor Code',
    suggestedPrice: 79,
    monetized: true,
    paymentProvider: 'honor',
    status: 'gated',
    liveDate: '2026-07-15',
    accentColor: 'rose',
  },
  'hiring-compliance': {
    slug: 'hiring-compliance',
    route: '/tools/hiring-compliance',
    title: 'California Hiring Compliance Toolkit',
    shortTitle: 'Hiring Toolkit',
    description: 'California hiring compliance toolkit — ban-the-box (AB 1008) compliant job posting review, offer letter templates, background check process, and salary history ban (SB 1162) compliance.',
    targetKeyword: 'California hiring compliance AB 1008 ban the box SB 1162 employer',
    lawRef: 'Gov. Code § 12952 (AB 1008) / Labor Code § 432.3 (SB 1162)',
    badge: 'AB 1008 + SB 1162',
    suggestedPrice: 99,
    monetized: true,
    paymentProvider: 'honor',
    status: 'gated',
    liveDate: '2026-07-15',
    accentColor: 'cyan',
  },
}

export const spokeList = Object.values(spokeRegistry)
export const liveSpokes = spokeList.filter(s => s.status === 'live')
export const gatedSpokes = spokeList.filter(s => s.status === 'gated')
